  
Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
  GitHubRepo:
    Type: String
    Default: aws-check
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: GitHub repository branch
  GitHubToken:
    Type: String
    NoEcho : true,
    Description: GitHub repository OAuth personal token

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Check Cloudformation GitHub Configuration
      Parameters:
      - GitHubOwner
      - GitHubRepo
      - GitHubBranch
      - GitHubToken

    ParameterLabels:
      GitHubOwner:
        default: My GitHub Account Name
      GitHubRepo:
        default: My GitHub Repository Name
      GitHubBranch:
        default: My GitHub Repository Branch
      GitHubToken:
        default: My GitHub Repository Secret Token

Resources:
  CheckPipelineArtifactS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CheckCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: Check-CodePipeline
      RoleArn: !GetAtt CheckCodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref CheckPipelineArtifactS3Bucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Version: '1'
              Provider: GitHub
            Configuration:
              Owner: !Ref GitHubOwner
              Repo: !Ref GitHubRepo
              Branch: !Ref GitHubBranch
              OAuthToken: !Ref GitHubToken
            OutputArtifacts:
              - Name: SourceApp
            RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceApp
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuiltApp
              Configuration:
                ProjectName: !Ref CheckCodeBuild
           
  CheckCodeBuild:
      Type: AWS::CodeBuild::Project
      Properties:
          Name: Check-CodeBuild
          ServiceRole: !GetAtt CheckCodeBuildRole.Arn
          Source:
              Type: CODEPIPELINE
          Environment:
              ComputeType: BUILD_GENERAL1_SMALL
              Image: "aws/codebuild/python:3.6.5"
              Type: LINUX_CONTAINER
              EnvironmentVariables:
                  - Name: ARTIFACT_BUCKET
                    Value: !Ref CheckPipelineArtifactS3Bucket
          Artifacts:
              Name: !Sub ${CheckPipelineArtifactS3Bucket}-Built
              Type: CODEPIPELINE

  CheckCodeBuildRole:
    Type: "AWS::IAM::Role"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
            reason: "This is iam role with * is ok for the CF validation"
          - id: W11
            reason: "This is iam role with * is ok for the CF validation"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "AWS-Check-CodeBuild-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
              - Effect: "Allow"
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${CheckPipelineArtifactS3Bucket}/*"
              - Effect: Allow
                Action:
                  - s3:*
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${CheckPipelineArtifactS3Bucket}"

  CheckCodePipelineRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F3
            reason: "This is iam role with * is ok for the CF validation"
          - id: W11
            reason: "This is iam role with * is ok for the CF validation"
    Properties:
      RoleName: CheckCodePipelineRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "CheckPipeline-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${CheckPipelineArtifactS3Bucket}"
              - Effect: "Allow"
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${CheckPipelineArtifactS3Bucket}/*"
              - Effect: "Allow"
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CheckCodeBuild}"
